blank_issues_enabled: false
contact_links:
  - name: Support
    url: https://github.com/MatthewRDangle/BattleCry/discussions/categories/support
    about: Please ask for help or report bugs here.
  - name: Feedback
    url: https://github.com/MatthewRDangle/BattleCry/discussions/categories/feedback
    about: Please leave any requests and application feedback here here.